export const ADD_SECRET_REQUEST = "ADD_SECRET_REQUEST"
export const ADD_SECRET_SUCCESS = "ADD_SECRET_SUCCESS"
export const ADD_SECRET_FAIL = "ADD_SECRET_FAIL"

export const GET_SECRET_REQUEST = "GET_SECRET_REQUEST"
export const GET_SECRET_SUCCESS = "GET_SECRET_SUCCESS"
export const GET_SECRET_FAIL = "GET_SECRET_FAIL"
